
#define GET_STATE "0"

#define SWITCH_POWER "1"
#define SWITCH_SLEEP_MODE "2"
#define POWER_OFF_VU "3"

#define TURN_ON_MAIN_RELAY "4"
#define TURN_OFF_MAIN_RELAY "5"

#define TURN_ON_SECONDARY_RELAY "6"
#define TURN_OFF_SECONDARY_RELAY "7"
