
#define SWITCH_POWER "0"

#define SWITCH_SLEEP_MODE "1"

#define TURN_ON_MAIN_RELAY "2"
#define TURN_OFF_MAIN_RELAY "3"

#define TURN_ON_SECONDARY_RELAY "4"
#define TURN_OFF_SECONDARY_RELAY "5"

#define GET_STATE "255"
