

#define GET_STATE "0"

#define SWITCH_POWER "1"
#define SWITCH_SLEEP_MODE "2"
#define POWER_OFF_VU "3"

#define TURN_ON_MAIN_RELAY "4"
#define TURN_OFF_MAIN_RELAY "5"

#define TURN_ON_SECONDARY_RELAY "6"
#define TURN_OFF_SECONDARY_RELAY "7"

#define TURN_OFF_VOLUME_PWM "8"

#define REVERSE_LOW_VOLUME_PWM "9"
#define REVERSE_MEDIUM_VOLUME_PWM "10"
#define REVERSE_HIGH_VOLUME_PWM "11"

#define FORWARD_LOW_VOLUME_PWM "12"
#define FORWARD_MEDIUM_VOLUME_PWM "13"
#define FORWARD_HIGH_VOLUME_PWM "14"